### ISSUE TITLE
File qpsnr.rb Error

### ISSUE THREAD

**Issue by diogopms** [hsanson/qpsnr#2]
vagrant@precise64:~/qpsnr$ ruby --version
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]

Error: 

qpsnr.rb:268:in `<main>': undefined method`size' for nil:NilClass (NoMethodError)

**Comment by diogopms** [comment]
any help me please ...

**Comment by hsanson** [comment]
What command are your running exactly?? I cannot reproduce this issue:

> ruby --version
> ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
> 
> ./qpsnr.rb
> Missing reference clip (-r) argument

**Comment by diogopms** [comment]
``` bash
vagrant@vagrant-debian-squeeze-64:~/qpsnr$ ls
LICENSE  Makefile  movies  obj  qpsnr  qpsnr.rb  README.md  scripts  src

```

``` bash
vagrant@vagrant-debian-squeeze-64:~/qpsnr$ pwd
/home/vagrant/qpsnr

```

Execute qpsnr ---> OK

``` bash
vagrant@vagrant-debian-squeeze-64:~/qpsnr$ /usr/bin/qpsnr 
[ERROR] Reference video not specified
vagrant@vagrant-debian-squeeze-64:~/qpsnr$ 

```

change this line:

``` ruby
#qpsnr_cmd = "/usr/bin/qpsnr -a ssim -I -m 10 -r #{ARGV.join(" ")}"
#qpsnr_cmd = "#{File.dirname(__FILE__)}/qpsnr "
qpsnr_cmd = "/usr/bin/qpsnr "
```

The error:

``` bash
./qpsnr.rb -m 400 -r movies/movie1.mp4 movies/movie2.mp4 
```

``` bash
/usr/bin/qpsnr -a ssim -J -G -m 400 -o colorspace=rgb:blocksize=8 -r movies/movie1.mp4 movies/movie2.mp4
Creating movie1 directory
[ERROR] Can't open file
./qpsnr.rb:269:in `<main>': undefined method `size' for nil:NilClass (NoMethodError)
```

**Comment by hsanson** [comment]
That qpsnr binary you use (/usr/bin/qpsnr) is the one provided with my source code? or is the original one? 
Make sure you are using my version that is modified to work with the ruby wrapper.

From the error it seems the output from qpsnr is not correct.

Is it possible to get your movie samples for testing on my side??????
